### ISSUE TITLE
Size mismatch between data and time

### ISSUE THREAD

**Issue by naelolaiz** [mattdavis90/hantek-wave-viewer#1]
Hi,

I tried the viewer with filed from a DSO2D15, but it fails:
```
Traceback (most recent call last):
  [...]
  File "hantek-wave-viewer/hantek_wave_viewer/__main__.py", line 5, in <module>
    main()
 [...]
  File "/usr/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 498, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (4000000,) and (4064000,)
```
The values are:
```
sampling depth:  4000000
seconds per sample: 4e-06
time size:  4000000
data1 size 4064000
data2 size 4064000
```
I tried with different dumps and it is always the same. I submitted one file here: https://drive.google.com/file/d/13J9sNVoYwQnq_i0Xxa1Q8ZOQbdxAwoYw/view

**Comment by naelolaiz** [comment]
Changing 
```
time = np.arange(0, wave.header.channel1.sampling_depth * seconds_per_sample, seconds_per_sample)
```
per
```
time = np.arange(0, len(data1) * seconds_per_sample, seconds_per_sample)[:-1]
```
as a quick hack, it seems to work.

**Comment by mattdavis90** [comment]
Hi @naelolaiz

Thanks for looking at this project and trying it out. Sorry that you hit issues. I've put together a patch that seems to work with the file you shared and also the other files I have. I can't replicate your issue using my scope but it still works for me with the patch applied so I'm happy.

If you can checkout the branch called [fix_timebase](https://github.com/mattdavis90/hantek-wave-viewer/tree/fix_timebase) and see if that works for you then I'll merge it into master.

Thanks

**Comment by naelolaiz** [comment]
Hi @mattdavis90 ,

First of all, thank you for doing and sharing the project! It is really useful! I could not find any other source with the format of these files. 

The code of the branch seems to work with all my files. Thanks a lot!

**Comment by mattdavis90** [comment]
Great. Glad it is working.

No problem. I searched quite a bit when I got the scope but couldn't find any documentation. There's a bit available around the VISA functionality over USB but I found that to be quite flaky when I tried it.

You posting made me revisit the project and I've realised that I have some code stashed that adds VCD file output support so that the the waveforms can be loaded into tools like GTKWave. Not sure how useful that is but I'll see how close it is to working and might update the project.
